export const GET_RECIPES = "GET_RECIPES";
export const GET_DETAIL_RECIPE = "GET_DETAIL_RECIPE";
export const GET_RECIPES_BY_NAME = "GET_RECIPES_BY_NAME";
export const CLEAN_DETAIL_RECIPE = "CLEAN_DETAIL_RECIPE";
export const GET_DIETS = "GET_DIETS";
